// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "PlaygroundTest",
  platforms: [
    .iOS("16.0")
  ],
  products: [
    .iOSApplication(
      name: "PlaygroundTest",
      targets: ["AppModule"],
      bundleIdentifier: "com.artisanalsoftware.PlaygroundTest",
      teamIdentifier: "34TKMKM889",
      displayVersion: "1.0",
      bundleVersion: "1",
      appIcon: .asset("AppIcon"),
      accentColor: .presetColor(.green),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ]
    )
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      path: "."
    )
  ],
  swiftLanguageVersions: [.version("6")]
)
